name: Another Site
favicon: null
layout_spectrum: 0.7599342016037554
typography_spectrum: 0.8124663759954274
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7587246061302722
  lightness: 0.8147358996793628
  saturation: 0.7506567286327481
  rhythmicContrast: 0.5541333567816764
purpose: []
